### PR TITLE
Merge pact files before upload + split pacts config to be consumerPact and providerPacts

### PR DESCRIPTION
**Pull request by lachatak**
Hi,

I as trying to use your maven plugin to download and upload pacts from the pactbroker.
I was facing with issues I tried to address:
- I am using ITV scala pact library which is unfortunately not merging pact files after the tests generated pacts like pact_jvm_consumer. They do the merge in their sbt pact upload plugin. But I am forced to use maven and your plugin satisfies my needs apart the fact that it is not merging. I added this piece of functionality into the PactFile. It checks the provider and the consumer for the loaded pact files and if two files has the same it merges them, writes the new file to the file system and finally the new file is used for uploading. If you use the plugin with pact_jvm it should have any negative effect but you could use with other pact generators like ITV's scalatest based.

The other thing is that I tried to use it in a multi module maven project where I have modules with consumers and producers. I would like to download pacts for producer tests and upload from consumer tests. With the current way of working the only way I could have this if I use profiles what I would like to avoid as much as possible. I believe it is an unnecessary complexity here.
All I need is a mvn clean install on the parent project and every submodule should know if it needs to download or upload. That is why I introduced consumerPacts and producerPacts config items. If both of them is missing nothing happens. If any of them or both is provide it behaves accordingly.
You can find an example here:
https://github.com/lachatak/consumer-driven-contract
The example is under development but the main thing is that on top level project a mvn clean install is enough and works nicely.

The third thing is that I had to set @Execute(phase = LifecyclePhase.NONE) as in a multi module project every tests were running 2 times. 

Feel free to use it in your project or just reject if you don't like.
I am open for further discussion :)
Obviously my change set has breaking changes as it doesn't support pacts config element any more.

Krisztian

### CODE REVIEW

**Comment by warmuuh** [comment]
Hi
Thanks for your work, it looks useful. It would have been nice to split these new features into different PRs though.
I will have a closer look at it in the next few days, but I would like to avoid breaking changes...

**Comment by lachatak** [comment]
Hi 
Have a look at it. If you like I could slice the features to separate PRs also keeping backward compatibility some how.
thx
k

**Comment by warmuuh** [comment]
hi
i had a look and i would like to integrate that, i just have some questions:
1) regarding the renaming of the pact-element: could [this](http://stackoverflow.com/questions/16540808/can-i-configure-multiple-plugin-executions-in-pluginmanagement-and-choose-from) work for you?
this is still a bit redundant in the sense of the phase though
2) can you explain why `@Execute(phase = LifecyclePhase.GENERATE_TEST_RESOURCES)` leads to 2 test-executions?
3) i think, putting the merging-functionality behind a property with default= false is safer, what do you think?
4) are you really sure that you merge pacts with same producer/consumer? BrokerRepositoryProvider::43 groups only by provider, no?

(i wont have any time in the next few weeks otherwise i would invest  some time to make those changes myself)

**Comment by lachatak** [comment]
Hi,
1) I suppose the first 2 points some how connected to each other. I saw that the configuration meant to be pushed under the execution which is fine. Probably I made a mistake that is why it didn't work for me. But! If you have a multi-module maven project you probably want to define everything at the top level and just add project specific configuration in the sub-modules. If you configure just the executions on the top level and try to run 'mvn clean install' at top level then the plugin fails as you didn't provided the pact directory on the parent. Obviously I don't want to do this at the parent as it belongs to the child. So I suppose still something is missing here. 
The other thing what I can do is just define the plugin at every child project without pre-configuring at the parent. This is something I have to investigate. But in this case some configuration will be duplicated across all the sub-mudules.
I will spend some time to look into it and I will get back to you with my findings.
3) property is fine. I like it.
4) Good point. I will fix this and adding test as well.

Thx the feedback
k

**Comment by lachatak** [comment]
I suppose not the @Execute(phase = LifecyclePhase.GENERATE_TEST_RESOURCES) is the problem but @Execute(phase = LifecyclePhase.TEST) on the top of the UploadPactMojo.

I have just tried your suggestions with executions:
http://stackoverflow.com/questions/16540808/can-i-configure-multiple-plugin-executions-in-pluginmanagement-and-choose-from

I followed the description in the post. I am using your latest plugin (0.0.8) There are 2 major issues:
1) Upload-artifact runs in verify phase in sub-modules and somehow every tests is executed twice. -> Two pact files are generated with the same content and eventually uploaded to the broker. Obviously duplicated pacts are the same so it won't effect anything in the broker but still not nice that it runs twice.  If I change the LifecyclePhase in the @Exceution to be NONE then it is alright. Runs just once with the previous configuration in every sub-module.
2) Well known issue. Merging pact not happens. 

So theoretically it works but something is not correct with the upload phasing.
I have created a branch so you could look into it:
https://github.com/lachatak/consumer-driven-contract/tree/execution_test

So the only thing we have left is to fix the phasing and the merge. 
I will look into it tomorrow.

k

**Comment by lachatak** [comment]
- Everything has been removed apart from the merging functionality and UploadPactsMojo phase.NONE. With the original phase.TEST every test runs twice in a multi-module project.
- producer consumer merging issue is fixed as well. 
- minor cleaning of not used imports

**Pull request merged**
